-- task 413: справочники фильтров вкладки «Расценки от подрядчиков (КП)».
-- Источник истины — миграция supabase/migrations/20260612_add_rates_registry_filter_options.sql.
--
-- kp_rates_registry_filter_objects (object_id, object_name) — только объекты, у которых
--   есть КП-расценки в реестре (distinct object_id из kp_rates_registry + имя объекта).
-- kp_rates_registry_filter_counterparties (counterparty_id, counterparty_name) — только
--   подрядчики, предоставившие КП (distinct counterparty_id из kp_rates_registry + имя).
--
-- kp_rates_registry_filter_tenders (tender_id, tender_desc, object_id) — только тендеры,
--   по которым есть расценки в реестре. Источник — миграция
--   supabase/migrations/20260715_add_rates_registry_filter_tenders.sql.
--
-- Списки «самораширяются»: появилась КП-расценка по новому объекту/подрядчику/тендеру → он в фильтре.
-- СУ-10 сюда не попадает (это другой источник — supply_rates_registry, task 412);
-- для него есть supply_rates_registry_filter_objects / _filter_tenders.
-- Зависит от kp_rates_registry (task 411).
