-- task 411: «Общий реестр расценок» (вкладка «Расценки от подрядчиков (КП)»).
-- Не таблица, а ПРЕДСТАВЛЕНИЕ над tender_counterparty_proposals с серверным дедупом,
-- чтобы фронт мог пагинировать/фильтровать/искать/сортировать на стороне БД.
-- Источник истины — миграция supabase/migrations/20260610_optimize_rates_registry.sql.
--
-- Колонки kp_rates_registry:
--   id                — стабильный синтетический ключ (md5 от ключа дедупа)
--   item_type         — 'material' | 'work'
--   item_name         — наименование позиции (cost_name из ВОР)
--   unit              — единица измерения
--   price             — цена за ед. (unit_price_materials / unit_price_works)
--   tender_id         — тендер
--   counterparty_id   — подрядчик
--   object_id         — объект (через tenders.object_id), может быть NULL
--   tender_desc       — tenders.work_description (для гиперссылки)
--   object_name       — objects.name
--   counterparty_name — counterparties.name
--   proposal_date     — дата КП
--
-- Дедуп: DISTINCT ON (tender_id, counterparty_id, item_type, kp_norm_name(item_name),
--   kp_norm_unit(unit)) с приоритетом по proposal_date DESC — одна базовая позиция,
--   встречающаяся в нескольких строках ВОР, в реестре одна.
--
-- kp_norm_name / kp_norm_unit — нормализация наименования/единицы (приближённо как
--   normalizeKey/normalizeUnit на фронте) — только для группировки.
--
-- kp_rates_registry_units — лёгкое представление distinct unit для фильтра.
--
-- Индексы (на нижележащих таблицах):
--   tender_counterparty_proposals(tender_id, counterparty_id, estimate_item_id,
--     proposal_date desc, unit_price_materials, unit_price_works)
--   tender_estimate_items USING gin (cost_name gin_trgm_ops), tender_estimate_items(unit)
--   tenders(object_id)
--
-- МАТЕРИАЛИЗОВАНО (миграция 20260902_rates_registry_materialized.sql).
-- Предупреждение из этого файла сбылось: DISTINCT ON по kp_norm_name()/kp_norm_unit()
-- считался на КАЖДЫЙ запрос, а одно открытие страницы давало шесть таких прогонов
-- (данные + два count + три справочника фильтров, которые читают это же вью).
--
-- Теперь:
--   kp_rates_registry_mv — MATERIALIZED VIEW с тем же самым SELECT;
--   kp_rates_registry    — тонкое вью `select * from kp_rates_registry_mv`,
--                          поэтому весь код работает с прежним именем;
--   индексы на MV: UNIQUE(id) (нужен для REFRESH CONCURRENTLY), (item_type, item_name, id),
--     (object_id), (counterparty_id), (tender_id), (price), (proposal_date),
--     GIN (item_name gin_trgm_ops) — под поиск ilike;
--   справочники фильтров переведены на чтение из MV.
--
-- Обновление: refresh_rates_registry() — REFRESH CONCURRENTLY обоих MV + отметка
-- времени в app_settings('rates_registry_refreshed_at'). Расписание pg_cron каждые
-- 10 минут плюс кнопка «Обновить» на странице.
--
-- ВАЖНО: у MV нет RLS и не работает security_invoker. Грант — только authenticated,
-- anon отозван явно (иначе материализация вернула бы анонимам доступ к ценам).
